### ISSUE TITLE
Get Latest TCN Library Integrated

### ISSUE THREAD

**Issue by madhavajay** [covid19risk/covidwatch-android#111]
Currently we have a pinned version of the TCN Library:
- implementation 'com.github.TCNCoalition:tcn-client-android:0.0.2'

The library itself is far further along on the dev branch:
https://github.com/TCNCoalition/tcn-client-android

The Minimal app is using a submodule which is pointing to the develop branch:
https://github.com/covid19risk/covidwatch-android-minimal

Should we do the same until we get some more stability in the library so that the changes can be integrated quickly into the UI app?

**Comment by Apisov** [comment]
Submodules are very convenient but introduce a bit of complexity in tracking latest changes, especially taking into account how the number of developers work on this project.

Having concrete version of the library helps to separate changes made in the app related to the library. Meaning if we see the app uses `0.0.2` then that code can access only that version of the lib. 

In the case of submodules, you can't be sure what commit from the library was used to make changes in the app itself. It is solvable though. People have to pull the `develop` branch of TCN library all the time but we lose that granularity using separate versions.

This is how I feel about but I'm open to discussion. For now I propose just use new version of TCN `0.0.3`.

**Comment by madhavajay** [comment]
Oh yeah, I hate submodules, but... I noticed they have made some improvements to them, and I wrote about it here over on the minimal repo:
https://github.com/covid19risk/covidwatch-android-minimal/pull/1

I believe you can now pin them to branches but it seems to require users to INIT them correctly to maintain the link to the tracked commit. The stackoverflow page is really long and I skimmed it but it seemed to work for me.

Currently on the iOS version we just point to develop and if the build breaks we fix it, but it means we're up to date immediately.

Just a suggestion, since currently due to the lack of official tagging I guess the Android app has some changes to integrate the new version.
