### ISSUE TITLE
Can we determine what country the user is in, or should we ask them?

### ISSUE THREAD

**Issue by freyley** [covid19risk/covidwatch-android#12]

**Comment by keturn** [comment]
The [Android BLE Guide](https://developer.android.com/guide/topics/connectivity/bluetooth-le) says:

> You must also declare the `ACCESS_FINE_LOCATION` permission, given that LE beacons are often associated with location. Without this permission, scans won't return any results.

So we'll necessarily have that permission in any case. Though getting the location _while in the background_ is `ACCESS_BACKGROUND_LOCATION`.

Google would really like people to use the [Location Provider](https://developers.google.com/location-context/fused-location-provider/) that's part of the Google Play Services. Do we have any constraints that mean we should not use a Google service? (e.g. privacy concerns, or markets that have Android with an alternative app provider.)

Turning a Location in to a country code requires a reverse-geocoder. The framework API docs have this to say about the Geocoder API:

> The Geocoder class requires a backend service that is not included in the core android framework. The Geocoder query methods will return an empty list if there no backend service in the platform. Use the isPresent() method to determine whether a Geocoder implementation exists.

I'm sure there's a variety of other indicators, other than the Location API, for various types of localization. What do we need to know for? How accurate does it have to be? How often does it need to be updated?

**Comment by freyley** [comment]
Within the app, we have a screen that shows health recommendations and is going to link to your country's health org (the CDC, etc)'s page for recommendations. 

We also want to localize the app, so we should also figure out what language you want to use from the OS rather than asking the user.

**Comment by filippkowalski** [comment]
We should use device local information about language to show proper language setting and direct to proper website. No need to call for Location just for this. 

Website address scan be set together with i18n files in strings.xml targeting specific language.

**Comment by freyley** [comment]
New ticket, #31 , for using locale to detect language and health authority
