### ISSUE TITLE
Better error handling on failed `submitReport` requests

### ISSUE THREAD

**Issue by nkumarcc** [covid19risk/covidwatch-android#126]
On a failed `submitReport` if not an `IOException` we won't go into a catch and we will retry infinitely. This can cause some bad results (eg we accidentally set off the rate limit for Firebase heavily). Put a limit on retries.

**Comment by madim** [comment]
I don't think that it will retry infinitely, but you're right that we should catch generic `Exception` instead of just `IOException` because [`execute()`](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-call/execute/) can also throw `IllegalStateException `
