### ISSUE TITLE
Add crashlytics to send error logs to Firebase

### ISSUE THREAD

**Issue by nkumarcc** [covid19risk/covidwatch-android#132]
Will help with logging with testers

**Comment by prasad79** [comment]
You can assign it to me. I can have a look at this issue.

**Comment by nkumarcc** [comment]
@crayne heads up you can link PR's to issues for easier tracking in the future. No biggie, but helps when the number of issues goes up :) 

Also @prasad79 sorry I didn't realize you were available for the task! In the future feel free to just assign the task to yourself and make the PR. If you need to be added to the Ghub message on Slack or ping here.
