### ISSUE TITLE
[UI/UX][HIGH PRI] Integrate UI/UX with BLE code

### ISSUE THREAD

**Issue by nkumarcc** [covid19risk/covidwatch-android#17]
Existing BLE Android repo: https://github.com/covid19risk/covidwatch-android
UX Repo merging from: https://github.com/covid19risk/covidwatch-android-ux

Right now we've added:
- Initiating Bluetooth permissions (it's buggy and not running properly rn, most of the code has been copied). This doesn't require asking permission from user
- Initiating location permissions, this requires a request and has been copied over from the above repo

Next:
- Debug Bluetooth permissions
- Actually run the advertising/receiving data

It looks like the best way to integrate this is to make a new branch in the https://github.com/covid19risk/covidwatch-android repo where we add our UI/UX code and connect it to the infra for tag.

**Comment by BurningAXE** [comment]
As we talked with @nkumarcc afawk this issue is done.
