### ISSUE TITLE
[i18n] Move all strings to strings.xml

### ISSUE THREAD

**Issue by nkumarcc** [covid19risk/covidwatch-android#19]
Will help long term for internationalizing app

Please do this in the `libcen-and-ux` branch

**Comment by keturn** [comment]
Related question: Strings are extracted to resources in this way for the purpose of internationalization, right? Does that mean that strings that should _not_ change for different languages should _not_ be resources?

i.e. strings used as constants or enumerated values such as

```xml
    <string name="preference_file_key">org.covidwatch.android.PREFERENCE_FILE_KEY</string>
```

**Comment by jamesjmtaylor** [comment]
> Related question: Strings are extracted to resources in this way for the purpose of internationalization, right? Does that mean that strings that should _not_ change for different languages should _not_ be resources?
> 
> i.e. strings used as constants or enumerated values such as
> 
> ```
>     <string name="preference_file_key">org.covidwatch.android.PREFERENCE_FILE_KEY</string>
> ```

That is correct.
