### ISSUE TITLE
[UI/UX][Master] Move towards new Figma

### ISSUE THREAD

**Issue by nkumarcc** [covid19risk/covidwatch-android#23]
Current link is here: https://www.figma.com/file/0qkRp3TrKBRnpEnmQeA5m4/Covid-Watch---App-v1.6?node-id=0%3A1

**Comment by BurningAXE** [comment]
This issue is too general. We should only use it as a parent and create more granular issues (probably per screen) that reference it.

**Comment by BurningAXE** [comment]
I will close this one as we more or less have the whole design covered now. We'll create more granular issues as problems/changes arise.
