### ISSUE TITLE
[BLE] Notify a user to turn Bluetooth back on if they turn it off

### ISSUE THREAD

**Issue by nkumarcc** [covid19risk/covidwatch-android#26]
If someone happens to turn off Bluetooth, even if they're not using app, notify them after some time to turn back on

**Comment by BurningAXE** [comment]
As stated in the PR I think we should use `BluetoothAdapter.ACTION_STATE_CHANGED` to detect when bluetooth has been turned off (https://stackoverflow.com/questions/9693755/detecting-state-changes-made-to-the-bluetoothadapter/9694138#9694138)
As I see it the best place to listen to this broadcast is in BluetoothManager which is constantly running as a foreground service.
Still, I would like @Apisov's opinion on this before we proceed with implementation. We also should consider if this should be implemented in the TCN library or in the client app(s).

**Comment by BurningAXE** [comment]
@jamesjmtaylor I intentionally reopened the issue to discuss how we should implement this.

**Comment by jamesjmtaylor** [comment]
> @jamesjmtaylor I intentionally reopened the issue to discuss how we should implement this.

Ah, my bad.

**Comment by Apisov** [comment]
I updated the bluetooth library and some code in the app to handle this use case. Check #95
