### ISSUE TITLE
Use the user's locale to determine language and relevant health authority

### ISSUE THREAD

**Issue by freyley** [covid19risk/covidwatch-android#31]

**Comment by filippkowalski** [comment]
Actually this will be done automatically as long as we provide `strings.xml` file with desired language. We just need to make sure that when we will be linking to the government website we will put the link in `strings-<country-code>.xml` so it can automatically fetched.

**Comment by redbassett** [comment]
I've added an action item for localization (#139), so I am closing this as it is captured in that issue.
