### ISSUE TITLE
[UI/UX] Tested Screen iter 2.0

### ISSUE THREAD

**Issue by nkumarcc** [covid19risk/covidwatch-android#45]
- Make datepicker buttons only show when appropriate radio button is picked
- Make Report button show when only the radio buttons/datepicker are filled
- Double check notifs to nearby device post infection

**Comment by BurningAXE** [comment]
I think the first two points are covered in Madi's design. I'm not sure what does the third one mean?

**Comment by madim** [comment]
done in https://github.com/covid19risk/covidwatch-android/pull/65
