### ISSUE TITLE
Add side menu

### ISSUE THREAD

**Issue by BurningAXE** [covid19risk/covidwatch-android#47]
Add a button in the app bar which opens a menu with the items from the design: https://www.figma.com/file/0qkRp3TrKBRnpEnmQeA5m4/Covid-Watch---App-v1.6?node-id=36%3A394
It's OK for the items to not work for now.
This should happen in MainActivity so the menu is present on every screen. Use navigation drawer from Material Design. In our design the menu is on the right but in Material Design it's on the left so it's OK to be there until we discuss it with the designer.

**Comment by BurningAXE** [comment]
@imshentastic I think your work may be duplicated by what @madim has done. Can you please check his PR: https://github.com/covid19risk/covidwatch-android/pull/65

**Comment by madim** [comment]
done in https://github.com/covid19risk/covidwatch-android/pull/65
