### ISSUE TITLE
Replace old app icon with the new logo

### ISSUE THREAD

**Issue by BurningAXE** [covid19risk/covidwatch-android#59]
Replace the old "Tags" launcher icon with the new Covid Watch icon: https://www.dropbox.com/sh/rbty2an2zid6fla/AABkal72BP_dY3b7RF8m7TJra?dl=0

Preferably continue support for Adaptive Icons: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

**Comment by nkumarcc** [comment]
This has been done.
