### ISSUE TITLE
When are you going to come out with the first release?

### ISSUE THREAD

**Issue by eabase** [covid19risk/covidwatch-android#6]
...a dev version would be fine too.

**Comment by nkumarcc** [comment]
Goal is end next week

**Comment by E3V3A** [comment]
Whats the status of this?

**Comment by nkumarcc** [comment]
Usable versions of the app are available in the `develop` branch and have been constantly been updated, we're working on getting it deployed in a test env.

Are you guys contributors or looking to test? If you'd like pull the develop branches and give us feedback in the form of issues!

**Comment by redbassett** [comment]
As of [v1.0-alpha](https://github.com/covid19risk/covidwatch-android/releases/tag/1.0-alpha) we have an official release of the app, albeit being an alpha that must be manually built. While we are not yet stable and in production, I would move that this issue is resolved.

**Comment by redbassett** [comment]
Closing this for now as resolved. A repo member can reopen if it should remain.
