### ISSUE TITLE
[BLE] Ensure bluetooth service is always running

### ISSUE THREAD

**Issue by BurningAXE** [covid19risk/covidwatch-android#70]
Currently the bluetooth service is BluetoothManager is started when the app starts. However, if the device restarts and the user does not explicitly start the app, service will not work. We need to ensure it does.
As of v2.3.0 WorkManager supports running foreground services through it which will ensure service persists through app/device restarts: https://developer.android.com/topic/libraries/architecture/workmanager/advanced/long-running
So I think this is the best approach to solve the problem. Again, I would like @apisov's take on this. Also, will this be implemented in the TCN library or on the client side!?

**Comment by nkumarcc** [comment]
@BurningAXE @Apisov @madhavajay where does this stand?

**Comment by Apisov** [comment]
@nkumarcc It looks like we fixed it in the library so when we integrate it it should work.
