### ISSUE TITLE
Notify user of positive contacts even if app is not running

### ISSUE THREAD

**Issue by BurningAXE** [covid19risk/covidwatch-android#72]
Check if notifications of positive contacts are received even if app is not running

**Comment by madim** [comment]
@BurningAXE I'll try to do that using WorkManager, but in the long run I think it's better if server will send us a notification and then we will act on that?

**Comment by BurningAXE** [comment]
@madim I don't think our architecture will allow that. Currently ContactEvents are kept on the device and only "infected" ones are uploaded. Then other devices download infected ContactEvents and compare them with what's in their local database. If there's a match - notify user. As the server is only aware of "infected" ContactEvents, it cannot know who should be notified. Which is intentional and part of the privacy preservation.
BTW, we have a WorkManager that downloads from Firebase every 3 hours. I think it should work and notify user even when app is not running. I made this task before getting familiar with this. But anyway, we need to make sure it works.
