### ISSUE TITLE
Clean git from .idea folders

### ISSUE THREAD

**Issue by Apisov** [covid19risk/covidwatch-android#8]
'.idea' is a dev-machine-specific folder from IDE which is bad to push because every dev will have to remove automatically-changed by IDE files under this folders.

# TODO 
- [x] Update .gitignore file
- [x] Possibly, update the project folder structure as we have redundant level of folders. We could only keep the `CowidWatch` folder and make it the root of this repository

**Comment by keturn** [comment]
A _subset_ of the files in `.idea` are machine-specific. I will find an already-configured `.idea` folder very useful for knowing I'm working with the correct run configurations and project standards.

I've found recent versions of the IDE provide an appropriate `.idea/.gitignore` that excludes the local storage and settings (though the one here does lack a few lines I've seen in other projects, but those projects were probably in other languages).

If changes to `.idea/` are popping up in git diff I think it's worth checking if they're things other developers will need too.

**Comment by keturn** [comment]
I see what you mean about the folder structure, though. The extra folder is confusing to Android Studio when a new dev like me just checks it out.

**Comment by Apisov** [comment]
Having the `.idea` folder is very uncommon practice(at least in the Android development). But I definitely can see your point why some things from that folder would be nice to have shared between developers. Code formatting is one big important thing.
