### ISSUE TITLE
Crash after restart phone

### ISSUE THREAD

**Issue by prasad79** [covid19risk/covidwatch-android#80]
**OS: Android 8.0
Device: Samsung Galaxy A3**

I see a crash once the phone is restarted:

Logs:

> 
> 2020-04-17 08:13:31.370 12395-12395/? E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: org.covidwatch.tags.android, PID: 12395
>     java.lang.RuntimeException: Unable to create application org.covidwatch.android.CovidWatchApplication: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.covidwatch.tags.android/org.tcncoalition.tcnclient.BluetoothService }: app is in background uid UidRecord{21b9432 u0a106 RCVR idle procs:1 seq(0,0,0)}
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6065)
>         at android.app.ActivityThread.-wrap1(Unknown Source:0)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
>         at android.os.Handler.dispatchMessage(Handler.java:105)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6944)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
>      Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.covidwatch.tags.android/org.tcncoalition.tcnclient.BluetoothService }: app is in background uid UidRecord{21b9432 u0a106 RCVR idle procs:1 seq(0,0,0)}
>         at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
>         at android.app.ContextImpl.startService(ContextImpl.java:1484)
>         at android.content.ContextWrapper.startService(ContextWrapper.java:663)
>         at org.covidwatch.android.ble.BluetoothManagerImpl.startService(BluetoothManager.kt:112)
>         at org.covidwatch.android.CovidWatchApplication.configureAdvertising(CovidWatchApplication.kt:64)
>         at org.covidwatch.android.CovidWatchApplication.onCreate(CovidWatchApplication.kt:93)
>         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6062)
>         at android.app.ActivityThread.-wrap1(Unknown Source:0) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764) 
>         at android.os.Handler.dispatchMessage(Handler.java:105) 
>         at android.os.Looper.loop(Looper.java:164) 
>         at android.app.ActivityThread.main(ActivityThread.java:6944) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by nkumarcc** [comment]
This looks relevant:
https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten

@jamesjmtaylor @Apisov, where does this lie in the world of "this is Bluetooth, Zsombor Pavlo own" vs "Android app owns"?

**Comment by jamesjmtaylor** [comment]
@nkumarcc I think this one lies at least partially in our court.  If the library doesn't support launching a foreground service however then they'll need to make changes as well.  I have a PR up addressing our side of the issue at https://github.com/covid19risk/covidwatch-android/pull/83
