### ISSUE TITLE
ANR in org.covidwatch.tags.android

### ISSUE THREAD

**Issue by madim** [covid19risk/covidwatch-android#92]
Description: Crashed when launching the app from Androdi Studio
Device: Samsung A3 2017, Android 8

Crash logs:
https://gist.github.com/madim/7ae2998cac9051743a6d5c2925ea7630

Might possibly relate to: https://github.com/covid19risk/covidwatch-android/issues/80#event-3244660757

**Comment by prasad79** [comment]
which branch is this error from?

I don't see "Context.startForegroundService" call (causing the crash) in the master or develop branch?

**Comment by madim** [comment]
@prasad79 I'm not sure if it is related to this crash, but I was able to reproduce ANR in develop. It happens every time you launch the app from Android Studio

It is probably related to how we start and stop BluetoothManager (Service), because if we comment it out, ANR goes away

**Comment by Apisov** [comment]
There is a bug indeed.
We should use only `bindService` and `unbindService` methods.

**Comment by Apisov** [comment]
I'll update the library to the new version.
Plus fix some things related to this in the `BluetoothManager`
